Repository microsoft/simplechat, pull requests merged in 2025-09, with the labels that each got.

#411 Agents and actions modal updates
  application/single_app/app.py
  application/single_app/config.py
  application/single_app/functional_tests/AGENT_CITATIONS_PER_MESSAGE_FIX.md
  application/single_app/functional_tests/AGENT_MODEL_DISPLAY_FIXES.md
  application/single_app/functional_tests/CONVERSATION_ID_DISPLAY_FIX.md
  application/single_app/functional_tests/test_form_clear_fix.py
  application/single_app/functional_tests/test_openapi_truncation_fix.py
  application/single_app/functional_tests/test_plugin_duplication_fix.py
  application/single_app/functional_tests/test_plugin_validation_compatibility.py
  application/single_app/functional_tests/test_sql_plugin_validation_fix.py
  application/single_app/functions_personal_actions.py
  application/single_app/json_schema_validation.py
  application/single_app/requirements.txt
  application/single_app/route_backend_plugins.py
  application/single_app/semantic_kernel_loader.py
  application/single_app/semantic_kernel_plugins/openapi_plugin.py
  application/single_app/static/images/favicon.ico
  application/single_app/static/js/plugin_modal_stepper.js
  application/single_app/templates/_plugin_modal.html
  documentation/AGENT_MODEL_DISPLAY_FIXES copy.md
  documentation/ENHANCED_WORLD_NEWS_AGENT_INSTRUCTIONS.md
  documentation/LARGE_API_RESPONSE_ENHANCEMENT.md
  documentation/MESSAGE_METADATA_LOADING_FIX.md
  documentation/PLUGIN_DUPLICATION_BUG_FIX.md
  documentation/SQL_PLUGIN_VALIDATION_FIX.md
  documentation/WORLD_NEWS_EUROPE_QUERY_ISSUE_ANALYSIS.md
Labels: bug, documentation, enhancement

#416 Updates to Terraform deployment
  README_orig.md
  deployers/terraform/.terraform.lock.hcl
  deployers/terraform/ai_search-index-user.json
  deployers/terraform/artifacts/ai_search-index-group.json
  deployers/terraform/artifacts/ai_search-index-public.json
  deployers/terraform/artifacts/ai_search-index-user.json
  deployers/terraform/main.tf
Labels: bug

#422 Enhanced citations for pdf video audio
  application/single_app/app.py
  application/single_app/config.py
  application/single_app/route_backend_documents.py
  application/single_app/route_backend_group_documents.py
  application/single_app/route_backend_public_documents.py
  application/single_app/route_enhanced_citations.py
  application/single_app/route_external_public_documents.py
  application/single_app/route_frontend_authentication.py
  application/single_app/static/js/chat/chat-citations.js
  application/single_app/static/js/chat/chat-enhanced-citations.js
  docs/fixes/ENHANCED_CITATIONS_PDF_MODAL_FIX.md
  docs/fixes/ENHANCED_CITATIONS_SERVER_SIDE_RENDERING_FIX.md
  docs/fixes/FILE_UPLOAD_EXECUTOR_FIX.md
  documentation/ENHANCED_CITATIONS_IMPLEMENTATION.md
  functional_tests/test_all_executor_fixes.py
  functional_tests/test_document_upload_functionality.py
  functional_tests/test_enhanced_citations_pdf_modal_fix.py
  functional_tests/test_enhanced_citations_server_side_rendering_fix.py
  functional_tests/test_final_executor_validation.py
  functional_tests/test_session_configuration.py
  functional_tests/test_session_upload.py
  functional_tests/test_upload_diagnosis.py
  test_enhanced_citations.py
  test_server_side_rendering.py
Labels: enhancement

#437 Development
  RELEASE_NOTES.md
  application/single_app/config.py
  application/single_app/route_backend_models.py
Labels: documentation

#444 Documentation and message table support
  RELEASE_NOTES.md
  application/single_app/config.py
  application/single_app/route_enhanced_citations.py
  application/single_app/route_frontend_chats.py
  application/single_app/route_frontend_public_workspaces.py
  application/single_app/semantic_kernel_plugins/openapi_plugin.py
  application/single_app/static/css/chats.css
  application/single_app/static/js/chat/chat-documents.js
  application/single_app/static/js/chat/chat-messages.js
  application/single_app/templates/manage_public_workspace.html
  docs/demos/Air Traffic Management.md
  docs/demos/Bridge Health Monitoring/Bridge Health Monitoring.md
  docs/demos/Enterprise Software Asset Management/Demo Questions for the ESAM Agent.md
  docs/demos/Enterprise Software Asset Management/ESAM Agent Instructions.md
  docs/demos/Enterprise Software Asset Management/Enterprise Software Asset Management.md
  docs/demos/Financial Mismanagement Investigations/Financial Mismanagement Investigations.md
  docs/demos/Nanomaterials and Smart Materials/Nanomaterials and Smart Materials.md
  docs/demos/Revenue Variance Analysis/Demo Questions for the RVA Agent.md
  docs/demos/Revenue Variance Analysis/Revenue Forecasting and Tax Refund Sensitivity.md
  docs/demos/Revenue Variance Analysis/Revenue Variance Analysis (RVA) Agent Instructions.md
  docs/demos/Revenue Variance Analysis/treasury_api_core_swagger.yaml
  docs/demos/Situational Awareness Reporting/Situational Awareness Reporting.md
  docs/features/COMPREHENSIVE_TABLE_SUPPORT.md
  docs/features/PUBLIC_WORKSPACE_GOTO_BUTTON_ENHANCEMENT.md
  docs/fixes/v0.229.014/PUBLIC_WORKSPACE_MANAGEMENT_PERMISSION_FIX.md
  docs/fixes/v0.229.014/PUBLIC_WORKSPACE_SCOPE_DISPLAY_ENHANCEMENT.md
  docs/fixes/v0.229.014/UNICODE_TABLE_RENDERING_FIX.md
  functional_tests/ascii_dash_table_test.html
  functional_tests/complete_table_support_test.html
  functional_tests/debug_ascii_conversion.js
  functional_tests/debug_header_issue.js
  functional_tests/final_validation.html
  functional_tests/table_processing_analysis.html
  functional_tests/table_validation_final.html
  functional_tests/test_comprehensive_table_support.py
  functional_tests/test_final_table_validation.py
  functional_tests/test_header_fix.js
  functional_tests/test_improved_ascii.js
  functional_tests/test_multi_workspace_document_access_fix.py
  functional_tests/test_new_approach.js
  functional_tests/test_psv_table_conversion.html
  functional_tests/test_table_markdown_analysis.py
  functional_tests/test_unicode_table_conversion.html
  functional_tests/test_unicode_table_conversion.py
Labels: bug

#448 V0.229 bug fixes (v0.229.019)
  application/single_app/app.py
  application/single_app/config.py
  application/single_app/route_backend_settings.py
  application/single_app/templates/_video_indexer_info.html
  application/single_app/templates/admin_settings.html
  docs/demos/Public Workspace/HR/Demo Questions for HR Processes.md
  docs/demos/Public Workspace/IT/Demo Questions for IT Operations and Security.md
  docs/demos/Public Workspace/Service Desk/Demo Questions for Service Desk Operations.md
  docs/demos/Semantic Kernel Agents/Semantic Kernel Questions.md
  docs/features/MULTIMEDIA_SUPPORT_REORGANIZATION.md
  docs/fixes/v0.229.019/COMPREHENSIVE_SECURITY_HEADERS_FIX.md
  docs/fixes/v0.229.019/DOCUMENT_INTELLIGENCE_TEST_CONNECTION_BUTTON_FIX.md
  docs/fixes/v0.229.019/EXTERNAL_HEALTH_CHECK_DUPLICATION_FIX.md
  docs/fixes/v0.229.019/STORAGE_CONTAINER_CREATION_FIX.md
  functional_tests/test_document_intelligence_test_button_fix.py
  functional_tests/test_external_health_check_duplication_fix.py
  functional_tests/test_multimedia_support_reorganization.py
  functional_tests/test_security_headers_comprehensive.py
  functional_tests/test_storage_container_creation_fix.py
  functional_tests/test_storage_container_creation_lightweight.py
Labels: bug

#458 Chat page top nav bug
  RELEASE_NOTES.md
  application/single_app/config.py
  application/single_app/templates/_sidebar_short_nav.html
  application/single_app/templates/base.html
  application/single_app/templates/chats.html
  docs/fixes/v0.229.060/CHAT_PAGE_TOP_NAV_LEFT_SIDEBAR_FIX.md
  route_backend_public_workspaces.py
Labels: bug

#469 Swagger lite
  application/single_app/app.py
  application/single_app/config.py
  application/single_app/example_swagger_usage.py
  application/single_app/plugin_validation_endpoint.py
  application/single_app/route_frontend_admin_settings.py
  application/single_app/route_frontend_authentication.py
  application/single_app/route_frontend_chats.py
  application/single_app/route_frontend_conversations.py
  application/single_app/route_frontend_feedback.py
  application/single_app/route_frontend_group_workspaces.py
  application/single_app/route_frontend_groups.py
  application/single_app/route_frontend_profile.py
  application/single_app/route_frontend_public_workspaces.py
  application/single_app/route_frontend_safety.py
  application/single_app/route_frontend_workspace.py
  application/single_app/route_migration.py
  application/single_app/route_openapi.py
  application/single_app/route_plugin_logging.py
  application/single_app/swagger_wrapper.py
  application/single_app/templates/_sidebar_nav.html
  application/single_app/templates/admin_settings.html
  application/single_app/templates/chats.html
  docs/features/AUTOMATIC_SWAGGER_SCHEMA_GENERATION.md
  docs/features/SWAGGER_ROUTE_WRAPPER_SYSTEM.md
  docs/features/v0.230.001/AUTOMATIC_SWAGGER_SCHEMA_GENERATION.md
  docs/features/v0.230.001/COMPREHENSIVE_TABLE_SUPPORT.md
  docs/features/v0.230.001/FULL_WIDTH_CHAT_SUPPORT.md
  docs/features/v0.230.001/PUBLIC_WORKSPACE_GOTO_BUTTON_ENHANCEMENT.md
  functional_tests/test_swagger_caching.py
  functional_tests/test_swagger_performance_impact.py
  functional_tests/test_swagger_wrapper_system.py
Labels: enhancement
