Repository microsoft/simplechat, pull requests merged in 2025-05, with the labels that each got.

#136 Update README.md
  README.md
Labels: documentation

#137 Update logo.png
  images/logo.png
Labels: documentation

#138 Update README.md
  README.md
Labels: documentation

#139 Update README.md
  README.md
Labels: documentation

#140 Update README.md
  README.md
Labels: documentation

#141 Update README
  README.md
  images/admin_settings-enable_and_configure_doc_classification.png
  images/admin_settings-enable_conversation_archiving.png
  images/admin_settings-enable_enhanced_citations.png
  images/admin_settings-enable_file_processing_logs.png
  images/admin_settings-enable_groups.png
  images/admin_settings-enable_video_file_support.png
  images/admin_settings-enable_workspace.png
  images/app_reg-app_role-create_group.png
  images/chat-classification_propagation.png
  images/chat-delete_conversation.png
  images/content_safety-in_action.png
  images/content_safety-maangement.png
  images/content_safety-settings.png
  images/content_safety-user_view.png
  images/cosmos_container-view_archived_conversation.png
  images/cosmos_container-view_archived_messages.png
  images/cosmos_container-view_specific_doc_file_processing_logs.png
  images/enterprise_app-add_user_to_role.png
  images/group_workspace-doc_list.png
  images/manage_group-add_member.png
  images/manage_group-group_details_as_owner.png
  images/manage_group-update_member_role.png
  images/my_groups-find_group-request_to_join.png
  images/my_groups-group_list.png
  images/storage_account-view_doc_for_citation_retrieval.png
  images/workflow-upload_process_audio_file.png
  images/workflow-upload_video_file.png
  images/workflow-view_and_update_classification.png
  images/workspace-doc_list.png
  images/workspace-enhanced_citation_tag.png
  images/workspace-prompt_edit.png
  images/workspace-prompt_list.png
Labels: documentation

#142 Update README
  README.md
  images/content_safety-cosmos_container.png
  images/content_safety-management.png
  images/content_safety-taking_action.png
Labels: documentation

#143 Update README with User Feedback
  README.md
  images/admin_settings-enable_user_feedback.png
  images/chat-feedback-negative.png
  images/feedback_review-list_all.png
  images/feedback_review-workflow.png
  images/my_feedback-list_all.png
  images/my_feedback-view_specific.png
Labels: documentation

#144 Update README with Audio Extraction
  README.md
  images/admin_settings-enable_audio_file_support.png
Labels: documentation

#146 Bug creating too many search returns
  application/single_app/config.py
  application/single_app/functions_documents.py
  application/single_app/functions_search.py
  application/single_app/route_backend_chats.py
Labels: bug

#147 Updated doc with (v0.212.78) term to (v0.212.79)
  README.md
  RELEASE_NOTES.md
Labels: documentation

#156 Dramatic improvement to document search
  application/single_app/config.py
  application/single_app/functions_content.py
  application/single_app/functions_search.py
Labels: enhancement

#150 Adding Container Gitub Actions Build
  .github/workflows/docker_image_publish.yml
  application/single_app/Dockerfile
Labels: enhancement

#159 Updated latest release
  README.md
  RELEASE_NOTES.md
Labels: documentation

#165 Update
  .github/workflows/docker_image_publish.yml
  README.md
  application/single_app/Dockerfile
  images/app_reg_edit_identity.png
  images/app_reg_secrets.png
  images/app_reg_settings.png
Labels: documentation

#166 Update OpenAPI Swagger file
  artifacts/open_api/openapi.yaml
Labels: bug, enhancement

#196 Development
  .github/workflows/docker_image_publish_dev.yml
  .github/workflows/enforce-dev-to-main.yml
  1deploysimplechat_banner.zip
  2deploysimplechat_banner.zip
  application/single_app/Dockerfile
  application/single_app/app.py
  application/single_app/config.py
  application/single_app/functions_documents.py
  application/single_app/functions_settings.py
  application/single_app/route_backend_users.py
  application/single_app/route_frontend_admin_settings.py
  application/single_app/route_frontend_authentication.py
  application/single_app/static/css/chats.css
  application/single_app/static/css/jquery.dataTables.min.css
  application/single_app/static/css/styles.css
  application/single_app/static/favicon.ico
  application/single_app/static/js/dark-mode.js
  application/single_app/templates/admin_settings.html
  application/single_app/templates/base.html
  application/single_app/templates/group_workspaces.html
  application/single_app/templates/workspace.html
  artifacts/open_api/openapi.yaml
  deploysimplechat_banner.zip
  images/icon.png
  images/logo_larger.png
Labels: bug, documentation, enhancement

#223 Development
  README.md
  RELEASE_NOTES.md
  application/single_app/config.py
  application/single_app/functions_documents.py
  application/single_app/route_backend_settings.py
  application/single_app/route_frontend_admin_settings.py
  application/single_app/static/css/chats.css
  application/single_app/static/css/simplemde.min.css
  application/single_app/static/js/admin/admin_settings.js
  application/single_app/static/js/chat/chat-documents.js
  application/single_app/static/js/simplemde/simplemde.min.js
  application/single_app/templates/admin_settings.html
  application/single_app/templates/chats.html
  application/single_app/templates/group_workspaces.html
  application/single_app/templates/workspace.html
Labels: bug, documentation, enhancement, security_improvement

#251 Redis
  README.md
  application/single_app/app.py
  application/single_app/functions_settings.py
  application/single_app/requirements.txt
  application/single_app/route_backend_settings.py
  application/single_app/route_frontend_admin_settings.py
  application/single_app/static/js/admin/admin_settings.js
  application/single_app/templates/admin_settings.html
Labels: documentation, enhancement
